### ISSUE TITLE
Fail to show account transaction history

### ISSUE THREAD

**Issue by bafu** [christian-oudard/mobilecoin-python-cli#2]
`mobcli` fails to show account transaction history.

**Steps to Reproduce**

1. Get Account ID

```
$ mobcli list

f259df starling
  address 48cfuaeDwGCFbqnxRaPUwhxePdL7ZQf8zzW3Z57oorky4jY78N4Akw9jtEdnj2Fn8DqFFw7o9LzzgHoNzULEsyUoWws5frbBxuJe4ZQVwH1
  18.8800 MOB (synced) 
```

2. Query history

```
$ mobcli history f259df

Traceback (most recent call last):
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/venv/bin/mobcli", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli.upstream/bin/mobcli", line 3, in <module>
    CommandLineInterface().main()
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/cli.py", line 45, in main
    command_func(**args)
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/cli.py", line 354, in history
    for txo in t['output_txos']
KeyError: 'output_txos'

```

**Environment**

* mobilecoin-python-cli: commit `9b948e4`
* full-service: `v1.0.0-pre.4` for Testnet

**Comment by christian-oudard** [comment]
This is a result of version mismatch between the python client and full-service. We'll soon have this code added to the full-service repo, so there won't be further version mismatches.
