### ISSUE TITLE
Fail to send MOBs to an address

### ISSUE THREAD

**Issue by bafu** [christian-oudard/mobilecoin-python-cli#3]
`mobcli` fails to show account transaction history.

**Steps to Reproduce**

1. Get Account ID

```
$ mobcli list

f259df starling
  address 48cfuaeDwGCFbqnxRaPUwhxePdL7ZQf8zzW3Z57oorky4jY78N4Akw9jtEdnj2Fn8DqFFw7o9LzzgHoNzULEsyUoWws5frbBxuJe4ZQVwH1
  18.8800 MOB (synced) 
```

2. Send MOBs to an address

    2.1. The address `4Xhj-qPCY` is a desktop wallet.
    2.2. I can use my desktop wallet to send MOBs to the address `4Xhj-qPCY`.
    2.3. Both the sender/receiver wallets in 2.2 ran on Testnet.

```
$ mobcli send f259df 0.01 4XHjrDy7HhpGHqL4r6deqdq4jf8faUXWqxLUJVchKcqATbGgjZweCwidkJCcpqQocusRr56yFtnnXKuyGHkCyhESjWDUwrJktdMHKmKqPCY 
Sending 0.0100 MOB from account f259df starling
to address 4XHjrDy7HhpGHqL4r6deqdq4jf8faUXWqxLUJVchKcqATbGgjZweCwidkJCcpqQocusRr56yFtnnXKuyGHkCyhESjWDUwrJktdMHKmKqPCY
Fee is 0.0100 MOB, for a total amount of 0.0200 MOB.
Confirm? (Y/N) Y
Traceback (most recent call last):
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/client.py", line 49, in _req
    response_data = r.json()
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/venv/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/venv/bin/mobcli", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli.upstream/bin/mobcli", line 3, in <module>
    CommandLineInterface().main()
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/cli.py", line 45, in main
    command_func(**args)
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/cli.py", line 433, in send
    transaction_log = self.client.build_and_submit_transaction(account_id, amount, to_address)
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/client.py", line 216, in build_and_submit_transaction
    r = self._req({
  File "/home/bafu/codes/signal/testnet-full-service-release-linux-penryn-1.0.0-pre.4/mobilecoin-python-cli/mobilecoin/client.py", line 51, in _req
    raise ValueError('API returned invalid JSON:', r.text)
ValueError: ('API returned invalid JSON:', 'Could not get value Error("missing field `recipient_public_address`", line: 0, column: 0)')
```

**Environment**

* mobilecoin-python-cli: commit `9b948e4`
* full-service: `v1.0.0-pre.4` for Testnet

**Comment by christian-oudard** [comment]
This is a result of version mismatch between the python client and full-service. We'll soon have this code added to the full-service repo, so there won't be further version mismatches.

**Comment by christian-oudard** [comment]
Current develop branch has synchronized versions of full-service and the python CLI. https://github.com/mobilecoinofficial/full-service/tree/develop

**Comment by bafu** [comment]
@christian-oudard Thank you for your update.

After updating `mobcli`, I met another error and opened a new issue here:

https://github.com/mobilecoinofficial/full-service/issues/154
